### ISSUE TITLE
Authentication on NA servers

### ISSUE THREAD

**Issue by Zelli** [EloGank/lol-php-api#8] opened 2015-01-10 03:02 UTC
Hi there,

I dont know if this api is still maintained, but I got problems to get the connection to NA servers running. EUW works fine, but on NA server I always get 

EloGankAPI.ERROR: Client #2 (NA) cannot authenticate : Error when connecting to server: Connection refused [] []

In synchronous mode I get this php error also: 

PHP Warning:  stream_socket_client(): unable to connect to ssl://prod.na1.lol.riotgames.com:2099 (Connection refused) in /opt/lol-php-api/src/EloGank/Api/Client/RTMP/RTMPSocket.php on line 52

It seems like this is an error caused by certificates but I got no clue how to fix it.

**Comment by memelo** [comment] 2015-01-10 03:05
na2*

**Comment by RanadeepPolavarapu** [comment] 2015-01-10 03:06
This is actually not an issue by certificates, but because NA1 was migrate to NA2. If it persists then your IP is being blocked by CloudFlare NA. 

Use of this API is actually against Riot Games ToS now. Any app you make using this API if it's to get popular will be asked to be taken down followed by legal action because it causes stress on League platform.

**Comment by Zelli** [comment] 2015-01-10 03:09
I am completely aware of that. But they got an exception: You are allowed to retrieve live game data, at least names of the participants.

I was curious about that. Because the host system on that machine is windows and I was able to connect via the official lol launcher, but not from the virtual machine running linux using this api.

It works now and I am really thankful

**Comment by Divi** [comment] 2015-01-10 14:06
Hey everyone :),

Thanks for the answers. If I understood, the NA server has been changed for NA2 server, given by @memelo ?

If it confirmed, I'll update the [config.yml.dist](https://github.com/EloGank/lol-php-api/blob/master/config/config.yml.dist) file.

**Comment by Zelli** [comment] 2015-01-13 19:35
@Divi Thank you. btw. is someone able to connect to euw server with this api ? I cant since yesterday.

**Comment by memelo** [comment] 2015-01-13 19:41
Error when connecting to server: Connection timed out.. (firewall blocking?)

**Comment by Zelli** [comment] 2015-01-13 19:43
Nothing changed. EU West was down yesterday and after that it did not work anymore.

**Comment by RanadeepPolavarapu** [comment] 2015-01-13 19:44
@Zelli are you connecting from like AWS or some other hosting provider?

**Comment by Divi** [comment] 2015-01-13 19:47
I can't test right now (cause I've not the game on this computer), but you can try to connect to the EUW server from the desktop launcher and with wireshark extract the IP address.

**Comment by memelo** [comment] 2015-01-13 19:47
I'm using AWS(sa-east-1a) and with the same issue

**Comment by RanadeepPolavarapu** [comment] 2015-01-13 19:49
Ok I am using DO and I can confirm this issue as well. Today was patch day so I'm assuming some auth method was implemented to prevent connection? AWS is typically not blocked by CloudFlare NA & EU. DO is blocked by CF NA and CF EU, but the fact that AWS is being blocked is very weird.

**Comment by memelo** [comment] 2015-01-13 19:51
@Divi lol.properties (prod.euw1.lol.riotgames.com)

**Comment by RanadeepPolavarapu** [comment] 2015-01-13 19:52
None of the prod and login queue routes changed. Nor did their IPs. This issue is either Riot changed auth method or CF is blocking.

**Comment by memelo** [comment] 2015-01-13 19:54
telnet prod.euw1.lol.riotgames.com 2099
Trying 185.40.64.65...
(nothing...)

**Comment by Zelli** [comment] 2015-01-13 19:55
Well,

@RanadeepPolavarapu I am not connected from AWS. I tried to connect from 2 different servers and my home pc.

**Comment by RanadeepPolavarapu** [comment] 2015-01-13 19:59
Well I mean Telnet is essentially telling us if we can reach server. I can reach NA and EUW game servers from my school connection. I think the issue here lies in NA and EUW authentication. I will confirm this when I get home. I will test both NA and EUW from my home connection.

@Zelli Yeah you shouldn't be getting this issue from your home pc. Try telnet into NA and EUW from your home connection to test if it's a firewall problem.

Here is an example of successful telnet:  
	Ranadeeps-MacBook-Pro:~ RanadeepPolavarapu$ telnet prod.euw1.lol.riotgames.com 2099
	Trying 185.40.64.65...
	Connected to prod.euw1.lol.riotgames.com.
	Escape character is '^]'.
	 
	l
	Connection closed by foreign host.

**Comment by Divi** [comment] 2015-01-13 20:03
Well, I found a computer with LoL, but still to rev 4.18, the update will takes some time.  
I'll dump packets tonight to see the server error answer.

@RanadeepPolavarapu telnet on EUW with right port works for me.

**Comment by memelo** [comment] 2015-01-13 20:03
I can not reach server, I think there was a firewall blocking

**Comment by Divi** [comment] 2015-01-13 20:05
@memelo  Try `telnet 185.40.64.65 2099`, for example.

**Comment by Zelli** [comment] 2015-01-13 20:07
got only Trying 185.40.64.65... from my home computer. But login in launcher works fine.

**Comment by memelo** [comment] 2015-01-13 20:07
@Divi Trying 185.40.64.65... (not responding)

**Comment by Divi** [comment] 2015-01-13 20:09
@memelo Seems weird.

**Comment by RanadeepPolavarapu** [comment] 2015-01-13 20:11
Ok I just launched an AWS EC2 instance and tested the EUW ip. EUW is being blocked from AWS. CF EU is to blame for this.

**Comment by memelo** [comment] 2015-01-13 20:11
@Divi firewall blocking my ip, sure!

**Comment by Divi** [comment] 2015-01-13 20:12
@memelo Indeed :

``` bash

[2015-01-13 20:11:23] EloGankAPI.INFO: Client async #2 (EUW) is connected [] []
[2015-01-13 20:11:23] EloGankAPI.INFO: Client async #4 (EUW) is connected [] []
[2015-01-13 20:11:23] EloGankAPI.INFO: Client async #5 (EUW) is connected [] []
[2015-01-13 20:11:23] EloGankAPI.INFO: Client #3 (EUW): in login queue (EUW), #7 [] []
[2015-01-13 20:11:23] EloGankAPI.INFO: Client #6 (EUW): in login queue (EUW), #9 [] []
[2015-01-13 20:11:23] EloGankAPI.INFO: Client #1 (EUW): in login queue (EUW), #28 [] []
[2015-01-13 20:11:27] EloGankAPI.INFO: Client async #1 (EUW) is connected [] []
[2015-01-13 20:11:27] EloGankAPI.INFO: Client async #3 (EUW) is connected [] []
[2015-01-13 20:11:27] EloGankAPI.INFO: Client async #6 (EUW) is connected [] []
[2015-01-13 20:11:28] EloGankAPI.INFO: 6/6 clients successfully connected [] []
[2015-01-13 20:11:28] EloGankAPI.INFO: Listening on *:8080 [] []
```

**Comment by Divi** [comment] 2015-01-13 20:15
@memelo Your server location is in EUW ?

**Comment by memelo** [comment] 2015-01-14 00:29
@Divi my aws? sa-east-1a (brazi - sao paulo)

**Comment by Divi** [comment] 2015-01-14 09:00
@memelo Seems Riot implemented geo IP firewall or, like @RanadeepPolavarapu said, an ISP firewall. Can you use a proxy/VPN to try this theory ?
If it works, I'll try to implement a feature to configure a proxy for the server connections.

**Comment by Zelli** [comment] 2015-01-14 12:08
@Divi Well, if it is a geo ip firewall, wouldnt I be able to connect from my local pc with this api ? But this isnt possible at the moment.

**Comment by Divi** [comment] 2015-01-14 12:18
@Zelli Indeed if you are in EUW. Can you paste here the full log please ?

**Comment by Zelli** [comment] 2015-01-14 12:47
@Divi Yes i am from Germany. Here is my full api log:

[2015-01-14 13:45:00] EloGankAPI.WARNING: You use the slow mode (synchronous), you can use the fast mode (asynchronous) by setting the configuration "client.async.enabled" to "true" [] []
[2015-01-14 13:45:00] EloGankAPI.INFO: Starting clients... [] []
[2015-01-14 13:45:05] EloGankAPI.ERROR: Client #1 (EUW) cannot authenticate : Error when connecting to server: Connection timed out [] []
[2015-01-14 13:45:08] EloGankAPI.INFO: Client #2 (NA) is connected [] []
[2015-01-14 13:45:08] EloGankAPI.ALERT: Only 1/2 client successfully connected [] []
[2015-01-14 13:45:08] EloGankAPI.INFO: Listening on *:10000 [] []

**Comment by memelo** [comment] 2015-01-14 14:51
@Divi lol client in my home(brazil too) works, I think that is not geoip.

**Comment by Divi** [comment] 2015-01-14 15:02
@Zelli @memelo Hmm, I don't see the problem.
There are some report of DNS issues in the LoL forum, maybe it isn't related to a third party API connection, but Riot server connection.

**Comment by Zelli** [comment] 2015-01-14 15:05
@Divi well, with direct ip connection dns issue should be the problem

**Comment by Divi** [comment] 2015-01-14 15:17
@Zelli great ! Don't forget to edit your `config/config.yml` file :+1: 
@memelo Can you test with your home connection ?

**Comment by Zelli** [comment] 2015-01-14 15:48
@Divi sorry, I had some brain lag, I meant it did not work with IP either.

**Comment by Divi** [comment] 2015-01-14 15:51
@Zelli ahah, no problem. Have you flush your DNS ? On Windows `ipconfig /flushdns`.

**Comment by Zelli** [comment] 2015-01-14 16:34
@Divi I already tried that

**Comment by memelo** [comment] 2015-01-14 16:47
@Divi Client #1 (EUW) cannot authenticate : Error when connecting to server: Tempo esgotado para conexão(Connection timed out) [] []

PS: home connection
PS2: lol client connects normally with the same account

**Comment by Zelli** [comment] 2015-01-14 16:49
@Divi @memelo Seems like they changed something about the authentication process so the api cant connect.

**Comment by RanadeepPolavarapu** [comment] 2015-01-14 16:58
Now that patch day is finished can someone test with other regions excluding KR? This will confirm if it's a firewall issue or auth method issue.

**Comment by Divi** [comment] 2015-01-14 16:58
@Zelli I can connect to servers with the API, so it's a middleware issue.
@memelo I think the desktop client has a IP resolver, or something like this. You'll have to check with wireshark the IP connection address. I've not this issue, so I can't do the test.

**Comment by RanadeepPolavarapu** [comment] 2015-01-14 17:00
@Divi you can connect to EUW as well from your end via API?

**Comment by Divi** [comment] 2015-01-14 17:00
@RanadeepPolavarapu Yep, see logs [above](https://github.com/EloGank/lol-php-api/issues/8#issuecomment-69811107).

**Comment by RanadeepPolavarapu** [comment] 2015-01-14 17:02
@Divi ahh okay. So, this all seems like firewall issue then. 

I can confirm both both DO and AWS are being blocked.

**Comment by memelo** [comment] 2015-01-14 17:05
using the same connection (home)

client = works
api = Connection timed out

telnet(windows) = reach server
telnet(linux) = does not reach the server

ehehe

**Comment by RanadeepPolavarapu** [comment] 2015-01-14 17:07
:/ ok that's odd. I'll debug authentication  once I am home and will update you guys.

**Comment by Divi** [comment] 2015-01-14 17:10
It will be hard to fix this issue if I cannot reproduce it :-1:.
The auth is OK, it's a stream timeout, so connection issue (not software issue) thrown by the [RTMPSocket constructor](https://github.com/EloGank/lol-php-api/blob/master/src/EloGank/Api/Client/RTMP/RTMPSocket.php#L51).

Remember if you want to dump data for debug purpose : disable the async config (otherwise you won't able to see outputs).

**Comment by memelo** [comment] 2015-01-14 17:19
@Divi I can send you an account on my linux which is experiencing the issue for you to test, email?

**Comment by Divi** [comment] 2015-01-14 23:01
@memelo Sure, my email is on my profile (on the left). Let me a not working account, and if possible a working account for the API. I'll check this tomorrow.

**Comment by Divi** [comment] 2015-01-14 23:16
There is an official issue here : http://status.leagueoflegends.com/?en_US#euw
Try to change your DNS settings on your server/computer : https://developers.google.com/speed/public-dns/docs/using

**Comment by Zelli** [comment] 2015-01-15 01:01
@Divi that did not work. I dont think its a dns issue. Since the normal client work fine.

**Comment by Zelli** [comment] 2015-01-16 16:46
Anything new regarding this issue ?

**Comment by Divi** [comment] 2015-01-16 17:00
@Zelli No, I'm waiting for the @memelo server access.

**Comment by memelo** [comment] 2015-01-16 17:35
sorry @Divi, sent to your email! :)

**Comment by Divi** [comment] 2015-01-16 17:37
@memelo Got it, I'll check that tomorrow :+1:

**Comment by Divi** [comment] 2015-01-17 18:23
@mmlo Well, I've tried, but fail. Mainly because I'm not a root user (and it's normal, don't worry).

So you'll have to try :
* update your DNS in /etc/resolv.conf
* disable TCP timestamp by running this command (only until you reboot your server) : `echo 0 > /proc/sys/net/ipv4/tcp_timestamps`, if it doesn't work try this page : http://www.tmltechnologies.com/html-2012/index.php/linux-rescue-kits/82-secret/91-disable-tcp-timestamps-on-linux
* sync your server datetime.

The IP address is accessible, but only the port `2099` is closed. I don't know why, btw it's clearly not an application issue.

**Comment by mmlo** [comment] 2015-01-17 18:27
@Divi 

I did:
echo 0 > /proc/sys/net/ipv4/tcp_timestamps

and..
[2015-01-17 16:25:43] EloGankAPI.INFO: Client #1 (EUW): in login queue (EUW), #22 [] []
[2015-01-17 16:25:47] EloGankAPI.INFO: Client #1 (EUW) is connected [] []
[2015-01-17 16:25:47] EloGankAPI.INFO: 1/1 client successfully connected [] []
[2015-01-17 16:25:47] EloGankAPI.INFO: Listening on *:8080 [] []
worked! :)

Thanks

**Comment by Divi** [comment] 2015-01-17 18:28
@mmlo Excellent news :+1:
@Zelli @RanadeepPolavarapu Can you try the same thing ?

**Comment by RanadeepPolavarapu** [comment] 2015-01-17 18:32
@Divi Mine works fine and as you said it's not an application problem. On my end, my cloud hosting provider's IP range is blocked is by CloudFlare firewall.

**Comment by Divi** [comment] 2015-01-17 18:33
@RanadeepPolavarapu Oh I see. Sorry about that :/
Have you try a tunneling or VPN ?

**Comment by Zelli** [comment] 2015-01-17 18:34
@Divi Awesome, that really works.Thank You

**Comment by mmlo** [comment] 2015-01-17 18:34
my AWS re-connect normally too!

**Comment by Divi** [comment] 2015-01-17 18:36
Awesome :+1: !
Be careful, I don't know if the fix is permanent (after a reboot, for example).
I closed this issue, feel free to reopen it (or create new one).

**Closed by Divi** 2015-01-17 18:36 UTC
Labels: bug, connection
